// Lista de animais disponíveis para adoção
const animais = [
  {
    id: 1,
    nome: 'Bolinha',
    tipo: 'Cão',
    raca: 'Labrador Retriever',
    idade: 2,
    localizacao: 'Lisboa',
    descricao: 'O Bolinha é um cão muito brincalhão e carinhoso que adora passear e brincar com crianças. É extremamente sociável e dá-se bem com outros animais. Já está vacinado, desparasitado e esterilizado.',
    imagem: 'https://placedog.net/400/300?id=1',
  },
  {
    id: 2,
    nome: 'Mimi',
    tipo: 'Gato',
    raca: 'Persa',
    idade: 3,
    localizacao: 'Porto',
    descricao: 'A Mimi é uma gata tranquila e muito afetuosa que adora festas e colo. É ideal para apartamento e dá-se bem com famílias calmas. Já está vacinada e esterilizada.',
    imagem: 'https://placekitten.com/400/300',
  },
  {
    id: 3,
    nome: 'Fofo',
    tipo: 'Coelho',
    raca: 'Anão Holandês',
    idade: 1,
    localizacao: 'Coimbra',
    descricao: 'O Fofo é um coelho muito curioso e ativo que adora explorar e comer cenouras frescas. É muito dócil e habituado ao contacto humano. Ótimo companheiro para famílias com crianças.',
    imagem: 'https://placehold.co/400x300?text=Fofo',
  },
  {
    id: 4,
    nome: 'Rex',
    tipo: 'Cão',
    raca: 'Pastor Alemão',
    idade: 4,
    localizacao: 'Braga',
    descricao: 'O Rex é um cão leal e muito inteligente que aprende comandos com facilidade. É protetor da família e precisa de espaço para correr e exercitar. Já está vacinado e desparasitado.',
    imagem: 'https://placedog.net/400/300?id=15',
  },
  {
    id: 5,
    nome: 'Luna',
    tipo: 'Gato',
    raca: 'Siamês',
    idade: 2,
    localizacao: 'Setúbal',
    descricao: 'A Luna é uma gata muito comunicativa e sociável que adora atenção e companhia. Não gosta de ficar sozinha por muito tempo e é muito brincalhona. Já está vacinada e esterilizada.',
    imagem: 'https://placekitten.com/401/301',
  },
  {
    id: 6,
    nome: 'Pipo',
    tipo: 'Pássaro',
    raca: 'Caturra',
    idade: 5,
    localizacao: 'Faro',
    descricao: 'O Pipo é um pássaro muito falador e divertido que já sabe dizer várias palavras e adora música. É muito fácil de cuidar e gosta de interagir com as pessoas. Vem com gaiola incluída.',
    imagem: 'https://placehold.co/400x300?text=Pipo',
  },
  {
    id: 7,
    nome: 'Toby',
    tipo: 'Cão',
    raca: 'Beagle',
    idade: 1,
    localizacao: 'Évora',
    descricao: 'O Toby é um cão jovem cheio de energia e muito afectuoso. Adora brincar ao ar livre e fazer caminhadas longas. É muito sociável e adora conhecer pessoas novas. Já está vacinado.',
    imagem: 'https://placedog.net/400/300?id=42',
  },
  {
    id: 8,
    nome: 'Mel',
    tipo: 'Coelho',
    raca: 'Rex',
    idade: 2,
    localizacao: 'Aveiro',
    descricao: 'A Mel é uma coelha muito mansa e carinhosa com pelo muito suave e sedoso. Adora ser acarinhada e é muito calma. Perfeita para quem procura um animal de estimação tranquilo e fácil de cuidar.',
    imagem: 'https://placehold.co/400x300?text=Mel',
  },
];

export default animais;
